/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import com.mysql.jdbc.Connection;       //db connection
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import prtype.validations;

import prtype.DBconnection;

public class Cater extends javax.swing.JFrame {

    Connection con = null;                       
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public Cater() {
        initComponents();
        con = DBconnection.connect();
        tableload();
        setfullscreen();
        
        
    }
    
     public void setfullscreen() {

        this.setResizable(false);

        Toolkit kit = Toolkit.getDefaultToolkit();

        int xsize = (int) kit.getScreenSize().getWidth();
        int ysize = (int) kit.getScreenSize().getHeight();

        int x = (xsize * 84) / 100;
        int y = (ysize * 84) / 100;

        this.setSize(x, y);//set size

        //moving to the center
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int Width = this.getSize().width;
        int Height = this.getSize().height;

        int locationx = (dimension.width - Width) / 2;
        int locationy = (dimension.height - Height) / 2;

        this.setLocation(locationx, locationy);

    }
    public void tableload(){
        
        try {
            String sqq = "SELECT OrderID,CustomerName,ContactNumber,NumberOfGuests,Address,Description,Deposit,Due,PaymentStatus FROM Corder";
            pst = con.prepareStatement(sqq);
           rs = pst.executeQuery();
           
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
           
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JTextField();
        NumberOfGuests = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Deposit = new javax.swing.JTextField();
        DueDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        PaymentStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        OrderID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        duedate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order");
        setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setText("Order ID");

        CustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CustomerNameKeyTyped(evt);
            }
        });

        jLabel2.setText("Customer Name");

        jLabel3.setText("Contact Number");

        jLabel4.setText("Number of Guests");

        jLabel5.setText("Address");

        jLabel6.setText("Deposit");

        jLabel8.setText("Payment Status");

        jLabel9.setText("Description");

        ContactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContactNumberKeyTyped(evt);
            }
        });

        NumberOfGuests.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumberOfGuestsKeyTyped(evt);
            }
        });

        Deposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DepositKeyTyped(evt);
            }
        });

        DueDate.setDateFormatString("yyyy-MM-dd");

        jLabel10.setText("Due Date");

        PaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Payed", "Not Payed" }));

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane1.setViewportView(Description);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        OrderID.setText("Order ID");

        jButton1.setText("Add Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Search Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update Order");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Due Orders");

        jButton6.setText("Inventory");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DueDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(duedate))
                        .addGap(302, 302, 302))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ContactNumber)
                                .addComponent(CustomerName)
                                .addComponent(NumberOfGuests)
                                .addComponent(Address)
                                .addComponent(OrderID)
                                .addComponent(PaymentStatus, 0, 166, Short.MAX_VALUE)
                                .addComponent(Deposit))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(OrderID))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumberOfGuests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel10))
                    .addComponent(DueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       food2 f = new food2();    //food2 window
       f.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                String name = CustomerName.getText();                      // cater order registrations
                int cnumber = Integer.parseInt(ContactNumber.getText());        //getting data from text fields to variables
                int nog = Integer.parseInt(NumberOfGuests.getText());
                String address = Address.getText();
                String description = Description.getText();
                double deposit = Double.parseDouble(Deposit.getText());
                String strdue = ((JTextField)DueDate.getDateEditor().getUiComponent()).getText();
                String ps = PaymentStatus.getSelectedItem().toString();
                
                String cnum = Integer.toString(cnumber);
                String n = Integer.toString(nog);
                String dep = Double.toString(deposit);
                
                validations v1 = new validations();   // validations
                boolean vname = v1.vcus(name);
                boolean vnum = v1.vcus(cnum);
                boolean c = v1.vcus(n);
                boolean d = v1.vcus(address);
                boolean e = v1.vcus(description);
                boolean f = v1.vcus(dep);
                boolean g = v1.vcus(strdue);
                boolean h = v1.vcus(ps);
                
               /*System.out.println(name);
                System.out.println(cnumber);
                System.out.println(nog);
                System.out.println(address);
                System.out.println(description);
                System.out.println(deposit);
                System.out.println(strdue);
                System.out.println(ps);*/
                
                
        
        if(vname == true && vnum == true && c == true && d == true && e == true && f == true && g == true && h == true  ){
        try {
            String Sq = "INSERT INTO Corder (CustomerName,ContactNumber,NumberOfGuests,Address,Description,Deposit,Due,PaymentStatus) VALUES ('"+ name +"','"+ cnumber +"','"+ nog +"','"+ address +"','"+ description +"','"+ deposit +"','"+ strdue +"','"+ ps +"')";
            pst=con.prepareStatement(Sq);
            pst.execute();
            CustomerName.setText("");
            ContactNumber.setText("");
            NumberOfGuests.setText("");
            Address.setText("");
            Description.setText("");
            Deposit.setText("");
            DueDate.setToolTipText("");
            PaymentStatus.setToolTipText("");
            
            tableload();
        } catch (SQLException ex) {
            System.out.println(ex);
            
        }}else{
             CustomerName.setText("");
            ContactNumber.setText("");
            NumberOfGuests.setText("");
            Address.setText("");
            Description.setText("");
            Deposit.setText("");
            DueDate.setToolTipText("");
            PaymentStatus.setToolTipText("");
        }
        
                
                
             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();                            //   table data ->  text fields
        String id = jTable1.getValueAt(r, 0).toString();
        String nm = jTable1.getValueAt(r, 1).toString();
        String num = jTable1.getValueAt(r, 2).toString();
        String nog = jTable1.getValueAt(r, 3).toString();
        String add = jTable1.getValueAt(r, 4).toString();
        String des = jTable1.getValueAt(r, 5).toString();
        String dep = jTable1.getValueAt(r, 6).toString();
        String du = jTable1.getValueAt(r, 7).toString();
        String pss = jTable1.getValueAt(r, 8).toString();
        
        OrderID.setText(id);
        CustomerName.setText(nm);
        ContactNumber.setText(num);
        NumberOfGuests.setText(nog);
        Address.setText(add);
        Description.setText(des);
        Deposit.setText(dep);
        duedate.setText(du);
        PaymentStatus.setSelectedItem(pss);
    }//GEN-LAST:event_jTable1MouseClicked

    private void duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      int x = JOptionPane.showConfirmDialog(null, "Confirm Update");      // update cater order 
      if(x == 0){
          
                String id = OrderID.getText();
                String name = CustomerName.getText();
                int cnumber = Integer.parseInt(ContactNumber.getText());
                int nog = Integer.parseInt(NumberOfGuests.getText());
                String address = Address.getText();
                String description = Description.getText();
                double deposit = Double.parseDouble(Deposit.getText());
                
                String strdue2 = duedate.getText();
               // String strdue1 = ((JTextField)DueDate.getDateEditor().getUiComponent()).getText();
                String ps = PaymentStatus.getSelectedItem().toString();
                
                System.out.println(name);
                System.out.println(cnumber);
                System.out.println(nog);
                System.out.println(address);
                System.out.println(description);
                System.out.println(deposit);
                System.out.println(strdue2);
                System.out.println(ps);
                
                
          try {
              String ss = "UPDATE corder SET CustomerName = '"+ name +"' , ContactNumber = '"+ cnumber +"' , NumberOfGuests = '"+ nog +"' , Address = '"+ address +"' , Description = '"+ description +"' , Deposit = '"+ deposit +"' , Due = '"+ strdue2 +"' , PaymentStatus = '"+ ps +"' WHERE OrderID = '"+ id +"' ";
              pst = con.prepareStatement(ss);
              pst.execute();
              tableload();
          } catch (SQLException ex) {
              System.out.println(ex);
          }
                
                
                
      }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int x = JOptionPane.showConfirmDialog(null,"Confirm Delete");   // remove cater orders
       if(x == 0){
           String idd = OrderID.getText();
          try{
           String sss = "DELETE FROM corder WHERE OrderID = '"+ idd +"'";
           pst = con.prepareStatement(sss);
           pst.execute();
           tableload();
          }catch(SQLException ex){
              System.out.println(ex);
          }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String cont = ContactNumber.getText();                               // getting the info from database to jTable
        String sl = "SELECT * FROM corder WHERE ContactNumber = '"+ cont +"'";
        try {
            pst = con.prepareStatement(sl);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Cater.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ContactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactNumberKeyTyped
        char a = evt.getKeyChar();                  // validation  (not allowing the blank spaces)
        
        if(!(Character.isDigit(a) || a == KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_ContactNumberKeyTyped

    private void CustomerNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomerNameKeyTyped
       char b = evt.getKeyChar();
       
       if(!(Character.isLetter(b) || b == KeyEvent.VK_BACK_SPACE )){
           getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_CustomerNameKeyTyped

    private void NumberOfGuestsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumberOfGuestsKeyTyped
       char c = evt.getKeyChar();
       
       if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE)){
           getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_NumberOfGuestsKeyTyped

    private void DepositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DepositKeyTyped
        char d = evt.getKeyChar();
        
        if(!(Character.isDigit(d) || d == KeyEvent.VK_BACK_SPACE)){
            getToolkit().beep();
            evt.consume();
            
        }
    }//GEN-LAST:event_DepositKeyTyped

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {      // main method
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(food2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(food2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(food2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(food2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cater().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JTextField Deposit;
    private javax.swing.JTextArea Description;
    private com.toedter.calendar.JDateChooser DueDate;
    private javax.swing.JTextField NumberOfGuests;
    private javax.swing.JLabel OrderID;
    private javax.swing.JComboBox<String> PaymentStatus;
    private javax.swing.JTextField duedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
